# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-17 17:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='nom')),
                ('short_name', models.CharField(max_length=5, verbose_name='acronyme')),
            ],
            options={
                'verbose_name': 'filière',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nom du pays', max_length=50, verbose_name='nom')),
            ],
            options={
                'verbose_name': 'pays',
                'verbose_name_plural': 'pays',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='HighSchool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line1', models.CharField(help_text='Numéro, rue, voie, nom de société, etc.', max_length=100, verbose_name='adresse (ligne 1)')),
                ('line2', models.CharField(blank=True, help_text='Bâtiment, étage, lieu-dit, etc.', max_length=100, verbose_name='adresse (ligne 2)')),
                ('post_code', models.CharField(max_length=20, verbose_name='code postal')),
                ('city', models.CharField(max_length=50, verbose_name='ville')),
                ('name', models.CharField(help_text='Nom du lycée', max_length=100, verbose_name='nom')),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='internal.Country', verbose_name='pays')),
            ],
            options={
                'verbose_name': 'lycée',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='nom')),
            ],
            options={
                'verbose_name': 'niveau',
                'verbose_name_plural': 'niveaux',
            },
        ),
        migrations.CreateModel(
            name='Rope',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nom de la cordée', max_length=100, verbose_name='nom')),
            ],
            options={
                'verbose_name': 'cordée',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line1', models.CharField(help_text='Numéro, rue, voie, nom de société, etc.', max_length=100, verbose_name='adresse (ligne 1)')),
                ('line2', models.CharField(blank=True, help_text='Bâtiment, étage, lieu-dit, etc.', max_length=100, verbose_name='adresse (ligne 2)')),
                ('post_code', models.CharField(max_length=20, verbose_name='code postal')),
                ('city', models.CharField(max_length=50, verbose_name='ville')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='date de naissance')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='téléphone')),
                ('branch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='internal.Branch', verbose_name='filière')),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='internal.Country', verbose_name='pays')),
                ('high_school', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='internal.HighSchool', verbose_name='lycée')),
                ('level', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='internal.Level', verbose_name='niveau')),
            ],
            options={
                'verbose_name': 'lycéen',
                'ordering': ('user__last_name', 'user__first_name', 'high_school', 'level'),
            },
        ),
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line1', models.CharField(help_text='Numéro, rue, voie, nom de société, etc.', max_length=100, verbose_name='adresse (ligne 1)')),
                ('line2', models.CharField(blank=True, help_text='Bâtiment, étage, lieu-dit, etc.', max_length=100, verbose_name='adresse (ligne 2)')),
                ('post_code', models.CharField(max_length=20, verbose_name='code postal')),
                ('city', models.CharField(max_length=50, verbose_name='ville')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='date de naissance')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='téléphone')),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='internal.Country', verbose_name='pays')),
            ],
            options={
                'verbose_name': 'tuteur',
                'ordering': ('user__last_name', 'user__first_name'),
            },
        ),
        migrations.CreateModel(
            name='TutoringGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('high_school', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='internal.HighSchool', verbose_name='lycée')),
                ('level', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='internal.Level', verbose_name='niveau')),
            ],
            options={
                'verbose_name': 'groupe de tutorat',
                'verbose_name_plural': 'groupes de tutorat',
                'ordering': ('high_school', 'level'),
            },
        ),
        migrations.CreateModel(
            name='TutoringMeeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='date')),
                ('tutoring_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='internal.TutoringGroup', verbose_name='groupe de tutorat')),
            ],
            options={
                'verbose_name': 'séance de tutorat',
                'verbose_name_plural': 'séances de tutorat',
                'ordering': ('date', 'tutoring_group'),
            },
        ),
        migrations.AddField(
            model_name='tutor',
            name='tutoring_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='internal.TutoringGroup', verbose_name='groupe de tutorat'),
        ),
        migrations.AddField(
            model_name='tutor',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='utilisateur'),
        ),
        migrations.AddField(
            model_name='student',
            name='tutoring_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='internal.TutoringGroup', verbose_name='groupe de tutorat'),
        ),
        migrations.AddField(
            model_name='student',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='utilisateur'),
        ),
        migrations.AddField(
            model_name='highschool',
            name='rope',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='internal.Rope'),
        ),
    ]
