# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-27 11:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('internal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grade',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='level',
        ),
        migrations.RemoveField(
            model_name='tutoree',
            name='grade',
        ),
        migrations.AddField(
            model_name='tutoree',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='internal.Branch', verbose_name='filière'),
        ),
        migrations.AddField(
            model_name='tutoree',
            name='level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='internal.Level', verbose_name='niveai'),
        ),
        migrations.DeleteModel(
            name='Grade',
        ),
    ]
