# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-27 11:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('internal', '0002_auto_20170827_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutoree',
            name='level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='internal.Level', verbose_name='niveau'),
        ),
    ]
