# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-27 11:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internal', '0004_auto_20170827_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='short_name',
            field=models.CharField(max_length=5, verbose_name='acronyme'),
        ),
    ]
